name: npm publish
on:
  pull_request:

jobs:
  npm_publish:
    uses: ./.github/workflows/npm_publish.yml
  docker_publish:
    uses: ./.github/workflows/npm_publish.yml

  complete:
    if: always()
    needs: [ npm_publish, docker_publish ]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
