name: releas, publish to npm and dockerhub

on:
#  release:
#    types: [published]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm test
        uses: ./.github/workflows/test_wf.yml

      - name: docker image publish
        uses: ./.github/workflows/test_wf2.yml


